version: "3.8"

services:
  mariadb:
    image: mariadb:10.6
    container_name: erpnext_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - erpnet

  redis-cache:
    image: redis:7
    container_name: redis_cache
    networks:
      - erpnet

  redis-queue:
    image: redis:7
    container_name: redis_queue
    networks:
      - erpnet

  backend:
    image: frappe/erpnext:version-14
    container_name: erpnext_backend
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    environment:
      DB_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - erpnet

  frontend:
    image: frappe/erpnext:version-14
    container_name: erpnext_frontend
    depends_on:
      - backend
    ports:
      - "8000:8000"
    networks:
      - erpnet

volumes:
  mariadb_data:

networks:
  erpnet: