LOAD DATABASE
     FROM      mysql://migration_user:rootpassword@172.16.238.5:3306/blog_db
     INTO      postgresql://postgres:postgrespassword@172.16.238.6:5432/blog_db_migrated

INCLUDING ONLY TABLE NAMES MATCHING
     'wp_posts', 'wp_users', 'wp_comments', 'wp_terms',
     'wp_term_taxonomy', 'wp_term_relationships', 'wp_options',
     'wp_postmeta', 'wp_usermeta', 'wp_links', 'wp_commentmeta',
     'wp_termmeta', 'wp_actionscheduler_actions',
     'wp_actionscheduler_claims', 'wp_actionscheduler_groups',
     'wp_actionscheduler_logs'

WITH include drop, create tables, create indexes, reset sequences, foreign keys

SET work_mem to '64MB', maintenance_work_mem to '128MB'

CAST type datetime to timestamp using zero-dates-to-null,
     type date to date using zero-dates-to-null,
     type tinyint to smallint,
     type int to bigint

BEFORE LOAD DO
$$ CREATE SCHEMA IF NOT EXISTS public; $$;
