LOAD DATABASE
     FROM      mysql://migration_user:rootpassword@172.16.238.5:3306/ecommerce_db
     INTO      postgresql://postgres:postgrespassword@172.16.238.6:5432/ecommerce_db_migrated

WITH include drop, create tables, create indexes, reset sequences, foreign keys

SET work_mem to '128MB', maintenance_work_mem to '512MB'

CAST type datetime to timestamp using zero-dates-to-null,
     type date to date using zero-dates-to-null,
     type tinyint to boolean

BEFORE LOAD DO
$$ CREATE SCHEMA IF NOT EXISTS public; $$;
