services:
  redis:
    image: redis:7-alpine
    container_name: migrate-optima-redis
    ports:
      - "6379:6379"
    networks:
      - migration-net

  metadata-db:
    image: postgres:15-alpine
    container_name: migrate-optima-metadata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: migrate_optima_metadata
    ports:
      - "5434:5432"
    networks:
      - migration-net

networks:
  migration-net:
    external: true
    name: bullshit-nofocus_migration-net
