import { FRAMEWORK, type ToolProfile } from '../data/thesis';

/** Opens a print-friendly summary; user chooses &quot;Save as PDF&quot; from the print dialog. */
export function openPrintableRecommendation(tool: ToolProfile, description: string): void {
  const win = window.open('', '_blank');
  if (!win) return;

  const esc = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

  win.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Migration recommendation — ${esc(tool.name)}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; color: #1a1a2e; line-height: 1.6; }
    h1 { font-size: 1.4rem; color: #2d6a4f; border-bottom: 2px solid #3d8f6f; padding-bottom: 8px; }
    h2 { font-size: 1rem; color: #333; margin-top: 1.5rem; }
    .score { font-size: 2.5rem; font-weight: 700; color: #2d6a4f; }
    .badge { display: inline-block; background: #e8f4ef; color: #1e4d3a; padding: 3px 10px; border-radius: 4px; font-size: 0.8rem; font-weight: 600; margin-bottom: 1rem; }
    .desc { background: #f4faf7; border-left: 3px solid #3d8f6f; padding: 12px 16px; border-radius: 0 6px 6px 0; margin: 1rem 0; }
    .grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 10px; margin: 1rem 0; }
    .cat { background: #eef6f2; border-radius: 6px; padding: 10px; text-align: center; }
    .cat .val { font-size: 1.4rem; font-weight: 700; color: #2d6a4f; }
    .cat .lbl { font-size: 0.7rem; color: #555; margin-top: 4px; }
    .framework { background: #f9f9f9; border: 1px solid #ddd; border-radius: 6px; padding: 12px 16px; margin: 1rem 0; font-size: 0.85rem; }
    .footer { margin-top: 2rem; font-size: 0.75rem; color: #888; border-top: 1px solid #eee; padding-top: 1rem; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <div class="badge">Recommended tool (quiz + rubric scores)</div>
  <h1>Database migration tool recommendation</h1>
  <div class="score">${esc(tool.name)} &nbsp; <span style="font-size:1.2rem;color:#555">${tool.score} / 5.0</span></div>
  <h2>Summary</h2>
  <div class="desc">${esc(description)}</div>
  <h2>Detailed justification</h2>
  <p style="font-size:0.9rem">${esc(tool.justification)}</p>
  <h2>Category breakdown (rubric)</h2>
  <div class="grid">
    <div class="cat"><div class="val">${tool.schema}</div><div class="lbl">Schema</div></div>
    <div class="cat"><div class="val">${tool.data}</div><div class="lbl">Data</div></div>
    <div class="cat"><div class="val">${tool.transform}</div><div class="lbl">Transform</div></div>
    <div class="cat"><div class="val">${tool.performance}</div><div class="lbl">Performance</div></div>
    <div class="cat"><div class="val">${tool.operational}</div><div class="lbl">Operational</div></div>
  </div>
  <div class="framework">
    <strong>Framework:</strong> ${FRAMEWORK.criteriaCount} criteria across five weighted categories (see Methodology page).
    Empirical runs on three non-trivial MySQL exports (see repository and Methodology).
  </div>
  <div class="footer">
    Generated by Migration Tool Evaluator &nbsp;|&nbsp; ${new Date().toLocaleDateString()}
  </div>
  <script>
    setTimeout(function () { window.print(); }, 400);
  <\/script>
</body>
</html>`);
  win.document.close();
}
