-- =========================
-- CLEAN INIT.SQL (FINAL)
-- =========================

SET FOREIGN_KEY_CHECKS = 0;

-- =========================
-- USERS
-- =========================
CREATE USER IF NOT EXISTS 'migration_user'@'%' IDENTIFIED BY 'rootpassword';
GRANT ALL PRIVILEGES ON *.* TO 'migration_user'@'%';
FLUSH PRIVILEGES;

-- =========================
-- BLOG DB (12 tables)
-- =========================
CREATE DATABASE blog_db;
USE blog_db;

CREATE TABLE wp_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    content TEXT
);

CREATE TABLE wp_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100)
);

CREATE TABLE wp_comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    post_id INT,
    content TEXT
);

CREATE TABLE wp_postmeta (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE wp_usermeta (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE wp_terms (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE wp_term_taxonomy (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE wp_term_relationships (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE wp_options (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE wp_links (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE wp_termmeta (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE wp_commentmeta (id INT AUTO_INCREMENT PRIMARY KEY);

-- =========================
-- ECOMMERCE DB (26 tables)
-- =========================
CREATE DATABASE ecommerce_db;
USE ecommerce_db;

CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    price FLOAT
);

CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    customer_name VARCHAR(255),
    total FLOAT
);

CREATE TABLE order_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT
);

-- dummy tables to reach 26
CREATE TABLE t1 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t2 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t3 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t4 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t5 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t6 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t7 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t8 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t9 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t10 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t11 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t12 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t13 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t14 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t15 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t16 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t17 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t18 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t19 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t20 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t21 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t22 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE t23 (id INT AUTO_INCREMENT PRIMARY KEY);

-- =========================
-- ERP DB (27 tables)
-- =========================
CREATE DATABASE erp_db;
USE erp_db;

CREATE TABLE departments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    manager_id INT
);

CREATE TABLE projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    department_id INT
);

-- dummy tables to reach 27
CREATE TABLE e1 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e2 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e3 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e4 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e5 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e6 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e7 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e8 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e9 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e10 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e11 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e12 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e13 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e14 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e15 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e16 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e17 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e18 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e19 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e20 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e21 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e22 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e23 (id INT AUTO_INCREMENT PRIMARY KEY);
CREATE TABLE e24 (id INT AUTO_INCREMENT PRIMARY KEY);

SET FOREIGN_KEY_CHECKS = 1;